"""is_archive

Revision ID: 4a372cb0a7b1
Revises: a0cdd41dff08
Create Date: 2022-06-21 20:32:01.933883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a372cb0a7b1'
down_revision = 'a0cdd41dff08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_model', sa.Column('is_archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_model', 'is_archive')
    # ### end Alembic commands ###
